import Head from 'next/head'
import User from '../component/user'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

          <div className="row">
            <User userId={1} name='Oumar' img="https://bootdey.com/img/Content/avatar/avatar1.png"/>
            <User userId={2}  name='Fatimetou' img="https://bootdey.com/img/Content/avatar/avatar8.png"/>
          </div>


    </div>
  )
}
