import Head from 'next/head'
import User from '../component/user';

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>

          <div className="row">
            <User  name='AES' img="https://media.cybernews.com/images/featured/2020/12/What-is-AES-Encryption.jpg"/>
            <User  name='RSA' img="https://www.numerama.com//content/uploads/2010/01/rsacreators1.jpg"/>

          </div>


    </div>
  )
}
